# Generated by Django 6.0.5 on 2026-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
