# Generated by Django 5.2.11 on 2026-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_roadmap_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='topics_overview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
