# Generated by Django 5.2.11 on 2026-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('reset', 'Password Reset'), ('register', 'Registration')], max_length=10),
        ),
    ]
